change from present? to ruby-only check
I'm not sure where `present?` (a method defined in Rails) is being pulled in from, but for me, it's not:

```sh
NoMethodError: undefined method `present?' for nil (NoMethodError)

        elsif multi_tenant.present?
                          ^^^^^^^^^
```

I wonder if `elsif multi_tenant` is good enough, or do we need to explicitly check that if it has an `empty?` method, that the `empty?` method returns false (similar to what `present?` does)